"""empty message

Revision ID: 4f9daceff878
Revises: 36925e72bf89
Create Date: 2021-11-02 15:23:36.317209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f9daceff878'
down_revision = '36925e72bf89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('isdelete', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isdelete')
    # ### end Alembic commands ###
